
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>


G_BEGIN_DECLS

/* enumerations from "gck.h" */


GType gck_error_get_type (void);
#define GCK_TYPE_ERROR (gck_error_get_type())


GType gck_session_options_get_type (void);
#define GCK_TYPE_SESSION_OPTIONS (gck_session_options_get_type())


GType gck_builder_flags_get_type (void);
#define GCK_TYPE_BUILDER_FLAGS (gck_builder_flags_get_type())


GType gck_uri_error_get_type (void);
#define GCK_TYPE_URI_ERROR (gck_uri_error_get_type())


GType gck_uri_flags_get_type (void);
#define GCK_TYPE_URI_FLAGS (gck_uri_flags_get_type())

G_END_DECLS

/* Generated data ends here */

